Fix: custom errors
MLopezJ/asset-tracker-lwm2m-js pull request #9
Opened 2023-09-20 11:29 UTC by MLopezJ

Simplify the interface of custom errors

2023-09-20 11:59 UTC, coderbyheart requested changes

2023-09-20 11:59 UTC, coderbyheart commented on src/utils/getBat.ts
>  				message: 'error validating type',
This is also the same for all TypeErrors, so move it to the class.

2023-09-21 09:14 UTC, MLopezJ commented on src/converter.ts
>  	constructor({
Give explicit name to `warning` class

2023-09-21 09:14 UTC, MLopezJ commented on src/converter.ts
> +		nRFAssetTracker,
nRFAssetTracker is a name of proyect.

Refer to TypeScript type there as the type. Use `keyof`

2023-09-21 09:14 UTC, MLopezJ commented on src/converter.ts
> +		LwM2M,
LwM2M is the name of the protocol. Update variable name.

2023-09-21 09:14 UTC, MLopezJ commented on src/converter.ts
> +		super(`${nRFAssetTracker} object can not be created`)
Combine message with description

2023-09-22 12:29 UTC, coderbyheart approved these changes

2023-09-22 12:47 UTC, merged